"""artist modification

Revision ID: 498b88f6a344
Revises: 8637f1e6cbe6
Create Date: 2022-08-10 12:28:58.532014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498b88f6a344'
down_revision = '8637f1e6cbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
